name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      
    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "./rust -> target"
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        
    - name: Remove test dependencies
      shell: pwsh
      run: |
        $file = 'pubspec.yaml'
        $lines = Get-Content $file
        $newLines = [System.Collections.Generic.List[string]]::new()
        $i = 0
        while ($i -lt $lines.Count) {
            if ($lines[$i] -match '^\s*integration_test:\s*$') {
                $i += 2
            } else {
                $newLines.Add($lines[$i])
                $i++
            }
        }
        $newLines | Set-Content $file
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Build Windows
      run: flutter build windows --release
      
    - name: Upload BloomeeTunes EXE
      uses: actions/upload-artifact@v4
      with:
        name: BloomeeWindowsBuild
        path: build\windows\x64\runner\Release\BloomeeTunes.exe
