name: Build Custom Bloomee EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4'
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get
      
    - name: Build Windows App
      run: flutter build windows --release
      
    - name: Zip Release Folder
      # This zips the ENTIRE Release folder (including the missing DLLs and data folder)
      run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath bloomee_custom.zip
      shell: pwsh

    - name: Upload Bloomee ZIP
      uses: actions/upload-artifact@v4
      with:
        name: BloomeeCustomBuild
        # We now upload the .zip file instead of just the .exe
        path: bloomee_custom.zip
